spring:
  application:
    name: authorization-app
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        default_schema: auth
        show-sql: true
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
