server:
  port: 8087
  servlet:
    context-path: /api/auth
management:
  server:
    port: 8187
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: password
  liquibase:
    default-schema: auth
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: authorization-app
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"