version: '3.7'

services:
  postgres:
    image: 'postgres:15.1'
    container_name: 'database'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:
